version: '3'

services:
  auth-service:
    build: .
    image: bitnami/node:16.15.0
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/node-boilerplate
    ports:
      - '3000:3000'
    command: sh -c 'npm run dev'
    volumes:
      - .:/app

networks: 
  default: 
    external: 
      name: microservice-network
