version: '3'

services:
  user-service:
    build: .
    image: bitnami/node:16.15.0
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/node-boilerplate
    ports:
      - '3001:3001'
    volumes:
      - .:/app
    command: sh -c 'npm run seed && npm run dev'  

networks: 
  default: 
    external: 
      name: microservice-network
